### ISSUE TITLE
Hexo + Material + Github 搭建博客 | zdRan's blog

### ISSUE THREAD

**Issue by zdRan** [zdRan/zdran.github.io#9]
https://zdran.com/20180326.html 

 Hexo、Material、Github、搭建博客与配置

**Comment by Eajack** [comment]
不错~但是标签云、侧栏分类栏怎么弄呢？

**Comment by zdRan** [comment]
> @Eajack
> 不错~但是标签云、侧栏分类栏怎么弄呢？

在主题的配置文件里可以配置

```
sidebar:
  pages:
        标签云:
            name: 标签云
            link: "/tags"
            icon: tab
            divider: true
```
在 hexo 目录下的 source 文件夹内创建一个名为 tags 的文件夹。

然后在文件内创建一个名为 index.md 的 Markdown 文件。

在 index.md 文件内写入如下内容即可。

```
---
title: tags
date:
layout: tags
---
```

**Comment by zdRan** [comment]
> @nameNotNull
> 你的评论系统真不错

用的是 Gitalk

**Comment by leibatian** [comment]
你好 我这个 按照您的步骤  hexo g 就会报两条错误
 local hexo not found in  文件夹路径
 try running :'npm install hexo --save'

**Comment by zdRan** [comment]
@leibatian 你的hexo应该是没有安装成功。尝试执行一下：
`
npm install -g hexo
`

**Comment by honkerSK** [comment]
分类的_config.yml是否要配置一下?按照6.1 和6.2做完一直不显示

**Comment by honkerSK** [comment]
你好,  gitalk 设置了gitalk_client_id 和 gitalk_client_secret, 还是不行,提示 Error: Not Found.请问下这个怎么设置?

**Comment by zdRan** [comment]
> @honkerSK
> 你好,  gitalk 设置了gitalk_client_id 和 gitalk_client_secret, 还是不行,提示 Error: Not Found.请问下这个怎么设置?

1、看一下你的 OAuth application 申请是不是正确。Homepage URL和Authorization callback URL要写你的博客地址。
2、看一下_config.yml设置是不是正确。
这是我的配置：

```
comment:
    use:  "gitalk"
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    livere_data_uid:
    gitalk_repo: zdran.github.io  # git repo of the hexo
    gitalk_owner: zdRan # git repo's owner
    gitalk_client_id: xxxxxxxxxxxxxxxxx # github app client id 
    gitalk_client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # github app client secret 
    valine_leancloud_appId: # leancloud application app id
    valine_leancloud_appKey: # leancloud application app key

```
3、或者是你用的主题不支持 Gitalk。

**Comment by Saginume** [comment]
你好，我的主题也是material 按照您的设置修改了模板 为什么还是 error ？ 修改了gitalk_repo: gitalk_owner: gitalk_client_id: gitalk_client_secret:

**Comment by zdRan** [comment]
@Saginume 我也是直接按照官网上来的，上面是我的配置

**Comment by zdRan** [comment]
> @Saginume
> 你好，我的主题也是material 按照您的设置修改了模板 为什么还是 error ？ 修改了gitalk_repo: gitalk_owner: gitalk_client_id: gitalk_client_secret:

我也是直接按照官网上来的，下面的配置是我的配置。

**Comment by Saginume** [comment]
我用CDODING部署，github 上也显示1 user

**Comment by zdRan** [comment]
> @Saginume
> 我用CDODING部署，github 上也显示1 user

repo是存储评论的地方，一般直接用用你博客的仓库地址就可以。可以试试这种，  用户名.github.io

**Comment by Saginume** [comment]
'未找到相关的 Issues 进行评论'

**Comment by zdRan** [comment]
> @Saginume
> '未找到相关的 Issues 进行评论'

好像是你需要初始化一下，发布完成博客后，需要登录一下。或者说需要手动的提交一个Issues，参考一下这个：

[评论初始化](https://github.com/gitalk/gitalk/wiki/%E8%AF%84%E8%AE%BA%E5%88%9D%E5%A7%8B%E5%8C%96)

我是在博客的评论里登录了一下自己的github，然后手动打开了一下每个博客。

**Comment by zjt2005** [comment]
我的侧边栏显示不出来，得把页面拉到最下面才能显示。
是这个版本特有的BUg么

**Comment by zdRan** [comment]
> @zjt2005
> 我的侧边栏显示不出来，得把页面拉到最下面才能显示。
> 是这个版本特有的BUg么
> 

是不是你的配置不太对，一直没有发现过这个问题啊

**Comment by zjt2005** [comment]
> @zdRan
> > @zjt2005
> > 我的侧边栏显示不出来，得把页面拉到最下面才能显示。
> > 是这个版本特有的BUg么
> > 
> 
> 是不是你的配置不太对，一直没有发现过这个问题啊

额，抱歉，请问可以把你的配置发一下？实在感谢
已发帖求助[地址](https://github.com/viosey/hexo-theme-material/issues/728)

**Comment by zdRan** [comment]
> @zjt2005
> > @zdRan
> > > @zjt2005
> > > 我的侧边栏显示不出来，得把页面拉到最下面才能显示。
> > > 是这个版本特有的BUg么
> > > 
> > 
> > 是不是你的配置不太对，一直没有发现过这个问题啊
> 
> 额，抱歉，请问可以把你的配置发一下？实在感谢
> 已发帖求助[地址](https://github.com/viosey/hexo-theme-material/issues/728)

这是我的配置
```
# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto: cm.zdran@foxmail.com"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        标签云:
            name: 标签云
            link: "/tags"
            icon: tab
            divider: true
    article_num:
        use: true
        divider: false
    footer:
        divider: false
        theme: false
        support: false
        feedback: false
        material: false


```
